In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Data Frames").getOrCreate()

In [0]:
df = spark.read.options(inferSchema=True,header=True).csv('/FileStore/tables/StudentData.csv')
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [0]:
df.select('age','email','roll').show()

+---+--------------------+------+
|age|               email|  roll|
+---+--------------------+------+
| 28|Annika Hoffman_Na...|  2984|
| 29|Margene Moores_Ma...| 12899|
| 28|Jeannetta Golden_...| 21267|
| 29|Billi Clore_Mitzi...| 32877|
| 28|Claude Panos_Judi...| 41487|
| 28|Toshiko Hillyard_...| 52771|
| 28|Alberta Freund_El...| 61973|
| 28|Sheryll Towler_Al...| 72409|
| 28|Nicole Harwood_Cl...| 81492|
| 29|Judie Chipps_Clem...| 92882|
| 29|Dustin Feagins_Ma...|102285|
| 29|Maybell Duguay_Ab...|111449|
| 28|Latia Vanhoose_Mi...|122502|
| 29|Eda Neathery_Nico...|132110|
| 29|Margene Moores_Mi...|141770|
| 29|Claude Panos_Sant...|152159|
| 29|Mitzi Seldon_Jenn...|161771|
| 29|Taryn Brownlee_Mi...|171660|
| 29|Judie Chipps_Tary...|182129|
| 28|Ernest Rossbach_M...|192537|
+---+--------------------+------+
only showing top 20 rows

In [0]:
df.select(df.age,df.roll).show()

+---+------+
|age|  roll|
+---+------+
| 28|  2984|
| 29| 12899|
| 28| 21267|
| 29| 32877|
| 28| 41487|
| 28| 52771|
| 28| 61973|
| 28| 72409|
| 28| 81492|
| 29| 92882|
| 29|102285|
| 29|111449|
| 28|122502|
| 29|132110|
| 29|141770|
| 29|152159|
| 29|161771|
| 29|171660|
| 29|182129|
| 28|192537|
+---+------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import col, lit
df.select(col("email"),col('marks')).show()

+--------------------+-----+
|               email|marks|
+--------------------+-----+
|Annika Hoffman_Na...|   59|
|Margene Moores_Ma...|   62|
|Jeannetta Golden_...|   45|
|Billi Clore_Mitzi...|   29|
|Claude Panos_Judi...|   41|
|Toshiko Hillyard_...|   32|
|Alberta Freund_El...|   69|
|Sheryll Towler_Al...|   85|
|Nicole Harwood_Cl...|   64|
|Judie Chipps_Clem...|   51|
|Dustin Feagins_Ma...|   35|
|Maybell Duguay_Ab...|   53|
|Latia Vanhoose_Mi...|   27|
|Eda Neathery_Nico...|   55|
|Margene Moores_Mi...|   42|
|Claude Panos_Sant...|   27|
|Mitzi Seldon_Jenn...|   36|
|Taryn Brownlee_Mi...|   22|
|Judie Chipps_Tary...|   56|
|Ernest Rossbach_M...|   62|
+--------------------+-----+
only showing top 20 rows

In [0]:
df.select("*").show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
columns = df.columns

In [0]:
df.select(columns).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.select(df.columns[3:6]).show()

+------+------+-----+
|course|  roll|marks|
+------+------+-----+
|    DB|  2984|   59|
| Cloud| 12899|   62|
|    PF| 21267|   45|
|    DB| 32877|   29|
|   DSA| 41487|   41|
|   MVC| 52771|   32|
|   OOP| 61973|   69|
| Cloud| 72409|   85|
|   MVC| 81492|   64|
|   OOP| 92882|   51|
|   DSA|102285|   35|
|    DB|111449|   53|
|    DB|122502|   27|
|   MVC|132110|   55|
|    PF|141770|   42|
|    DB|152159|   27|
|   MVC|161771|   36|
|   OOP|171660|   22|
|    PF|182129|   56|
|    DB|192537|   62|
+------+------+-----+
only showing top 20 rows

In [0]:
df.select('age','marks',df.roll, col("email"), df.columns[4]).show()

+---+-----+------+--------------------+------+
|age|marks|  roll|               email|  roll|
+---+-----+------+--------------------+------+
| 28|   59|  2984|Annika Hoffman_Na...|  2984|
| 29|   62| 12899|Margene Moores_Ma...| 12899|
| 28|   45| 21267|Jeannetta Golden_...| 21267|
| 29|   29| 32877|Billi Clore_Mitzi...| 32877|
| 28|   41| 41487|Claude Panos_Judi...| 41487|
| 28|   32| 52771|Toshiko Hillyard_...| 52771|
| 28|   69| 61973|Alberta Freund_El...| 61973|
| 28|   85| 72409|Sheryll Towler_Al...| 72409|
| 28|   64| 81492|Nicole Harwood_Cl...| 81492|
| 29|   51| 92882|Judie Chipps_Clem...| 92882|
| 29|   35|102285|Dustin Feagins_Ma...|102285|
| 29|   53|111449|Maybell Duguay_Ab...|111449|
| 28|   27|122502|Latia Vanhoose_Mi...|122502|
| 29|   55|132110|Eda Neathery_Nico...|132110|
| 29|   42|141770|Margene Moores_Mi...|141770|
| 29|   27|152159|Claude Panos_Sant...|152159|
| 29|   36|161771|Mitzi Seldon_Jenn...|161771|
| 29|   22|171660|Taryn Brownlee_Mi...|171660|
| 29|   56|182129|Judie Chipps_Tary...|182129|
| 28|   62|192537|Ernest Rossbach_M...|192537|
+---+-----+------+--------------------+------+
only showing top 20 rows

In [0]:
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [0]:
df = df.withColumn('roll', col('roll').cast("String"))
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [0]:
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.withColumn('marks',col('marks')+10).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   69|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   72|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   55|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   39|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   51|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   42|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   79|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   95|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   74|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   61|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   45|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   63|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   37|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   65|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   52|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   37|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   46|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   32|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   66|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   72|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df = df.withColumn('updated_marks',col('marks')+10)
df.show()

+---+------+----------------+------+------+-----+--------------------+-------------+
|age|gender|            name|course|  roll|marks|               email|updated_marks|
+---+------+----------------+------+------+-----+--------------------+-------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|           72|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|           55|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|           51|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|           42|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|           79|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|           95|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|           74|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|           61|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|           45|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|           65|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|           52|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|           46|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|           32|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|           66|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|
+---+------+----------------+------+------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.withColumn('updated_marks',lit("happy")).show()

+---+------+----------------+------+------+-----+--------------------+-------------+
|age|gender|            name|course|  roll|marks|               email|updated_marks|
+---+------+----------------+------+------+-----+--------------------+-------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        happy|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        happy|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        happy|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        happy|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        happy|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        happy|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        happy|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        happy|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        happy|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|        happy|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        happy|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        happy|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|        happy|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        happy|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|        happy|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|        happy|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|        happy|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|        happy|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|        happy|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        happy|
+---+------+----------------+------+------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.withColumnRenamed("gender","sex").show()

+---+------+----------------+------+------+-----+--------------------+-------------+
|age|   sex|            name|course|  roll|marks|               email|updated_marks|
+---+------+----------------+------+------+-----+--------------------+-------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|           72|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|           55|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|           51|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|           42|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|           79|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|           95|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|           74|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|           61|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|           45|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|           65|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|           52|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|           46|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|           32|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|           66|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|
+---+------+----------------+------+------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.withColumnRenamed("gender","sex").withColumn("count",lit("USA")).withColumnRenamed("count","country").show()

+---+------+----------------+------+------+-----+--------------------+-------------+-------+
|age|   sex|            name|course|  roll|marks|               email|updated_marks|country|
+---+------+----------------+------+------+-----+--------------------+-------------+-------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|    USA|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|           72|    USA|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|           55|    USA|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|    USA|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|           51|    USA|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|           42|    USA|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|           79|    USA|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|           95|    USA|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|           74|    USA|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|           61|    USA|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|           45|    USA|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|    USA|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|    USA|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|           65|    USA|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|           52|    USA|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|    USA|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|           46|    USA|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|           32|    USA|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|           66|    USA|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|    USA|
+---+------+----------------+------+------+-----+--------------------+-------------+-------+
only showing top 20 rows

In [0]:
df.select(col('name').alias("Full Name")).show()

+----------------+
|       Full Name|
+----------------+
| Hubert Oliveras|
|Toshiko Hillyard|
|  Celeste Lollis|
|    Elenore Choy|
|  Sheryll Towler|
|  Margene Moores|
|     Neda Briski|
|    Claude Panos|
|  Celeste Lollis|
|  Cordie Harnois|
|       Kena Wild|
| Ernest Rossbach|
|  Latia Vanhoose|
|  Latia Vanhoose|
|     Neda Briski|
|  Latia Vanhoose|
|  Loris Crossett|
|  Annika Hoffman|
|   Santa Kerfien|
|Mickey Cortright|
+----------------+
only showing top 20 rows

In [0]:
df.filter(df.course=='DB').show()

+---+------+-----------------+------+-------+-----+--------------------+-------------+
|age|gender|             name|course|   roll|marks|               email|updated_marks|
+---+------+-----------------+------+-------+-----+--------------------+-------------+
| 28|Female|  Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|     Elenore Choy|    DB|  32877|   29|Billi Clore_Mitzi...|           39|
| 29|  Male|  Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|   Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|   Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|           37|
| 28|Female| Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|           72|
| 28|Female|      Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|           89|
| 28|  Male|    Kizzy Brenner|    DB| 381712|   36|Paris Hutton_Kena...|           46|
| 28|  Male| Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|           57|
| 29|  Male|     Paris Hutton|    DB| 481229|   57|Clementina Menke_...|           67|
| 28|Female| Mickey Cortright|    DB| 551389|   43|Tijuana Kropf_Jen...|           53|
| 28|Female|Leontine Phillips|    DB| 602404|   48|Neda Briski_Cheri...|           58|
| 28|Female|  Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|           89|
| 29|Female|     Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|           65|
| 29|  Male| Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|           86|
| 29|Female|  Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|           64|
| 29|  Male|     Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|           89|
| 28|  Male|   Annika Hoffman|    DB|1031544|   44|Dustin Feagins_So...|           54|
| 28|  Male|   Nicole Harwood|    DB|1211495|   28|Melani Engberg_Jc...|           38|
| 29|Female|     Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|           85|
+---+------+-----------------+------+-------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.filter(col("course")=='DB').show()

+---+------+-----------------+------+-------+-----+--------------------+-------------+
|age|gender|             name|course|   roll|marks|               email|updated_marks|
+---+------+-----------------+------+-------+-----+--------------------+-------------+
| 28|Female|  Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|     Elenore Choy|    DB|  32877|   29|Billi Clore_Mitzi...|           39|
| 29|  Male|  Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|   Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|   Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|           37|
| 28|Female| Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|           72|
| 28|Female|      Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|           89|
| 28|  Male|    Kizzy Brenner|    DB| 381712|   36|Paris Hutton_Kena...|           46|
| 28|  Male| Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|           57|
| 29|  Male|     Paris Hutton|    DB| 481229|   57|Clementina Menke_...|           67|
| 28|Female| Mickey Cortright|    DB| 551389|   43|Tijuana Kropf_Jen...|           53|
| 28|Female|Leontine Phillips|    DB| 602404|   48|Neda Briski_Cheri...|           58|
| 28|Female|  Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|           89|
| 29|Female|     Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|           65|
| 29|  Male| Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|           86|
| 29|Female|  Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|           64|
| 29|  Male|     Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|           89|
| 28|  Male|   Annika Hoffman|    DB|1031544|   44|Dustin Feagins_So...|           54|
| 28|  Male|   Nicole Harwood|    DB|1211495|   28|Melani Engberg_Jc...|           38|
| 29|Female|     Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|           85|
+---+------+-----------------+------+-------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.filter( (df.course=='DB') & (df.marks>50) ).show()

+---+------+------------------+------+-------+-----+--------------------+-------------+
|age|gender|              name|course|   roll|marks|               email|updated_marks|
+---+------+------------------+------+-------+-----+--------------------+-------------+
| 28|Female|   Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|           69|
| 29|  Male|   Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|  Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|           72|
| 28|Female|       Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|           89|
| 29|  Male|      Paris Hutton|    DB| 481229|   57|Clementina Menke_...|           67|
| 28|Female|   Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|           89|
| 29|Female|      Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|           65|
| 29|  Male|  Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|           86|
| 29|Female|   Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|           64|
| 29|  Male|      Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|           89|
| 29|Female|      Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|           85|
| 29|Female| Leontine Phillips|    DB|1432252|   67|Billi Clore_Shery...|           77|
| 28|Female|   Gonzalo Ferebee|    DB|1451513|   69|Claude Panos_Tame...|           79|
| 28|  Male|   Marylee Capasso|    DB|1611411|   96|Annika Hoffman_Lo...|          106|
| 29|  Male|    Alberta Freund|    DB|1671638|   98|Clementina Menke_...|          108|
| 28|Female|Priscila Tavernier|    DB|1722388|   86|Lawanda Wohlwend_...|           96|
| 29|  Male|    Dustin Feagins|    DB|1782045|   81|Cordie Harnois_To...|           91|
| 29|  Male|     Tijuana Kropf|    DB|1882795|   92|Hubert Oliveras_E...|          102|
| 28|  Male|   Ernest Rossbach|    DB|1901492|   54|Latia Vanhoose_Jc...|           64|
| 29|Female| Leontine Phillips|    DB|1972893|   64|Marylee Capasso_E...|           74|
+---+------+------------------+------+-------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.filter(df.course.isin(['DB','Cloud'])).show()

+---+------+----------------+------+------+-----+--------------------+-------------+
|age|gender|            name|course|  roll|marks|               email|updated_marks|
+---+------+----------------+------+------+-----+--------------------+-------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|           72|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|           95|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|
| 28|Female|       Kena Wild| Cloud|221750|   60|Mitzi Seldon_Jenn...|           70|
| 29|Female|     Anna Santos| Cloud|242254|   68|Jc Andrepont_Hube...|           78|
| 28|Female|  Maybell Duguay| Cloud|261439|   20|Nicole Harwood_Ju...|           30|
| 29|Female|    Cheri Kenney| Cloud|281408|   43|Annika Hoffman_Me...|           53|
| 29|Female|    Claude Panos| Cloud|302130|   59|Sheryll Towler_Le...|           69|
| 28|Female|     Anna Santos|    DB|311589|   79|Celeste Lollis_Mi...|           89|
| 28|  Male|   Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|           46|
| 28|  Male|Toshiko Hillyard|    DB|392218|   47|Leontine Phillips...|           57|
| 28|Female|   Kizzy Brenner| Cloud|402409|   27|Ernest Rossbach_G...|           37|
| 29|Female|  Somer Stoecker| Cloud|442028|   34|Taryn Brownlee_Ta...|           44|
| 29|  Male|    Paris Hutton|    DB|481229|   57|Clementina Menke_...|           67|
| 29|  Male|     Billi Clore| Cloud|512047|   76|Taryn Brownlee_Ju...|           86|
+---+------+----------------+------+------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.filter(df.course.startswith('D')).show()

+---+------+----------------+------+------+-----+--------------------+-------------+
|age|gender|            name|course|  roll|marks|               email|updated_marks|
+---+------+----------------+------+------+-----+--------------------+-------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|           51|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|           45|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|
| 28|Female|    Jc Andrepont|   DSA|232060|   58|Billi Clore_Abram...|           68|
| 29|Female|    Paris Hutton|   DSA|271472|   99|Sheryll Towler_Al...|          109|
| 28|Female|  Dustin Feagins|   DSA|291984|   82|Abram Nagao_Kena ...|           92|
| 28|Female|     Anna Santos|    DB|311589|   79|Celeste Lollis_Mi...|           89|
| 28|Female|Mickey Cortright|   DSA|342003|   44|Mitzi Seldon_Jean...|           54|
| 28|  Male|   Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|           46|
| 28|  Male|Toshiko Hillyard|    DB|392218|   47|Leontine Phillips...|           57|
| 29|Female|     Anna Santos|   DSA|411479|   42|Kena Wild_Mitzi S...|           52|
| 28|Female|  Maybell Duguay|   DSA|452141|   29|Leontine Phillips...|           39|
| 29|  Male|    Paris Hutton|    DB|481229|   57|Clementina Menke_...|           67|
| 29|Female|    Paris Hutton|   DSA|492159|   60|Nicole Harwood_Ma...|           70|
| 28|Female|Mickey Cortright|    DB|551389|   43|Tijuana Kropf_Jen...|           53|
+---+------+----------------+------+------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.filter(df.course.endswith('C')).show()

+---+------+----------------+------+-------+-----+--------------------+-------------+
|age|gender|            name|course|   roll|marks|               email|updated_marks|
+---+------+----------------+------+-------+-----+--------------------+-------------+
| 28|  Male|  Margene Moores|   MVC|  52771|   32|Toshiko Hillyard_...|           42|
| 28|  Male|  Celeste Lollis|   MVC|  81492|   64|Nicole Harwood_Cl...|           74|
| 29|Female|  Latia Vanhoose|   MVC| 132110|   55|Eda Neathery_Nico...|           65|
| 29|  Male|  Loris Crossett|   MVC| 161771|   36|Mitzi Seldon_Jenn...|           46|
| 28|Female|    Cheri Kenney|   MVC| 321816|   24|Kena Wild_Michell...|           34|
| 29|Female|  Jenna Montague|   MVC| 502585|   43|Hubert Oliveras_J...|           53|
| 29|  Male|  Tamera Blakley|   MVC| 651649|   92|Latia Vanhoose_To...|          102|
| 28|  Male|  Sheryll Towler|   MVC| 661079|   89|Tijuana Kropf_Mic...|           99|
| 29|  Male| Hubert Oliveras|   MVC| 672451|   28|Annika Hoffman_Mi...|           38|
| 29|  Male|  Jenna Montague|   MVC| 711153|   45|Marylee Capasso_H...|           55|
| 29|  Male|Jeannetta Golden|   MVC| 741875|   57|Sheryll Towler_Ch...|           67|
| 29|  Male|    Paris Hutton|   MVC| 752504|   22|Elenore Choy_Elen...|           32|
| 29|Female|  Margene Moores|   MVC| 761843|   48|Ernest Rossbach_M...|           58|
| 29|Female|  Taryn Brownlee|   MVC| 861849|   39|Billi Clore_Toshi...|           49|
| 28|Female|   Santa Kerfien|   MVC| 941783|   94|Paris Hutton_Naom...|          104|
| 29|  Male|     Abram Nagao|   MVC| 962235|   32|Jenna Montague_Go...|           42|
| 28|  Male|     Billi Clore|   MVC|1052566|   78|Naoma Fritts_Marg...|           88|
| 28|Female|  Nicole Harwood|   MVC|1061068|   82|Santa Kerfien_Hub...|           92|
| 29|Female|  Maybell Duguay|   MVC|1102536|   22|Somer Stoecker_Ma...|           32|
| 29|Female| Ernest Rossbach|   MVC|1201427|   80|Elenore Choy_Jenn...|           90|
+---+------+----------------+------+-------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
df.filter(df.name.contains('ly')).show()

+---+------+----------------+------+-------+-----+--------------------+-------------+
|age|gender|            name|course|   roll|marks|               email|updated_marks|
+---+------+----------------+------+-------+-----+--------------------+-------------+
| 29|Female|Toshiko Hillyard| Cloud|  12899|   62|Margene Moores_Ma...|           72|
| 28|  Male|Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|           57|
| 29|  Male|Toshiko Hillyard|   OOP| 521221|   77|Hubert Oliveras_L...|           87|
| 28|Female|Toshiko Hillyard|   DSA|1282835|   79|Somer Stoecker_To...|           89|
| 29|  Male|Toshiko Hillyard|   DSA|1791364|   50|Jc Andrepont_Nico...|           60|
| 28|  Male|Toshiko Hillyard|    PF|2162776|   54|Jenna Montague_Ni...|           64|
| 28|Female|Toshiko Hillyard|    DB|3602005|   54|Loris Crossett_An...|           64|
| 29|Female|Toshiko Hillyard|    PF|4032043|   28|Naoma Fritts_Cher...|           38|
| 28|  Male|Toshiko Hillyard| Cloud|4381862|   55|Anna Santos_Melan...|           65|
| 28|Female|Toshiko Hillyard| Cloud|4982864|   46|Michelle Ruggiero...|           56|
| 28|  Male|Toshiko Hillyard|   DSA|5992644|   77|Jenna Montague_Ti...|           87|
| 29|  Male|Toshiko Hillyard|   DSA|6371328|   91|Somer Stoecker_Ma...|          101|
| 29|Female|Toshiko Hillyard|   MVC|7912392|   38|Kena Wild_Alberta...|           48|
| 28|Female|Toshiko Hillyard|   MVC|8801160|   86|Neda Briski_Donna...|           96|
| 28|  Male|Toshiko Hillyard|    DB|9502901|   69|Kena Wild_Leontin...|           79|
| 29|Female|Toshiko Hillyard|   DSA|9792504|   68|Nicole Harwood_So...|           78|
+---+------+----------------+------+-------+-----+--------------------+-------------+

In [0]:
df.filter(df.name.like('%ly%')).show()

+---+------+----------------+------+-------+-----+--------------------+-------------+
|age|gender|            name|course|   roll|marks|               email|updated_marks|
+---+------+----------------+------+-------+-----+--------------------+-------------+
| 29|Female|Toshiko Hillyard| Cloud|  12899|   62|Margene Moores_Ma...|           72|
| 28|  Male|Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|           57|
| 29|  Male|Toshiko Hillyard|   OOP| 521221|   77|Hubert Oliveras_L...|           87|
| 28|Female|Toshiko Hillyard|   DSA|1282835|   79|Somer Stoecker_To...|           89|
| 29|  Male|Toshiko Hillyard|   DSA|1791364|   50|Jc Andrepont_Nico...|           60|
| 28|  Male|Toshiko Hillyard|    PF|2162776|   54|Jenna Montague_Ni...|           64|
| 28|Female|Toshiko Hillyard|    DB|3602005|   54|Loris Crossett_An...|           64|
| 29|Female|Toshiko Hillyard|    PF|4032043|   28|Naoma Fritts_Cher...|           38|
| 28|  Male|Toshiko Hillyard| Cloud|4381862|   55|Anna Santos_Melan...|           65|
| 28|Female|Toshiko Hillyard| Cloud|4982864|   46|Michelle Ruggiero...|           56|
| 28|  Male|Toshiko Hillyard|   DSA|5992644|   77|Jenna Montague_Ti...|           87|
| 29|  Male|Toshiko Hillyard|   DSA|6371328|   91|Somer Stoecker_Ma...|          101|
| 29|Female|Toshiko Hillyard|   MVC|7912392|   38|Kena Wild_Alberta...|           48|
| 28|Female|Toshiko Hillyard|   MVC|8801160|   86|Neda Briski_Donna...|           96|
| 28|  Male|Toshiko Hillyard|    DB|9502901|   69|Kena Wild_Leontin...|           79|
| 29|Female|Toshiko Hillyard|   DSA|9792504|   68|Nicole Harwood_So...|           78|
+---+------+----------------+------+-------+-----+--------------------+-------------+

In [0]:
# Quiz

In [0]:
student_data = spark.read.options(inferSchema=True,header=True).csv('/FileStore/tables/StudentData.csv')
student_data.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [0]:
student_data = student_data.withColumn('total marks', lit(120)).withColumn("average", (col('marks')/col('total marks'))*100)

In [0]:
student_data.show()

+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
|age|gender|            name|course|  roll|marks|               email|total marks|           average|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        120|49.166666666666664|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        120| 51.66666666666667|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|              37.5|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        120|24.166666666666668|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|26.666666666666668|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120| 57.49999999999999|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        120| 70.83333333333334|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        120|53.333333333333336|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|        120|              42.5|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        120|29.166666666666668|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        120|44.166666666666664|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|        120|              22.5|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        120| 45.83333333333333|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|        120|              35.0|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|        120|              22.5|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|        120|              30.0|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|        120|18.333333333333332|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|        120|46.666666666666664|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        120| 51.66666666666667|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
df_OOP = student_data.filter( (student_data.course=='OOP') & (student_data.average>80) )
df_OOP.show()

+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
|age|gender|              name|course|   roll|marks|               email|total marks|          average|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
| 28|  Male|    Jenna Montague|   OOP|3331161|   98|Leontine Phillips...|        120|81.66666666666667|
| 29|Female|Priscila Tavernier|   OOP|3902993|   99|Celeste Lollis_Bi...|        120|             82.5|
| 28|Female|      Judie Chipps|   OOP|5451977|   99|Tamera Blakley_Mi...|        120|             82.5|
| 29|  Male|    Margene Moores|   OOP|5621072|   97|Sheryll Towler_Ma...|        120|80.83333333333333|
| 29|  Male|      Jc Andrepont|   OOP|8022618|   97|Cordie Harnois_Ja...|        120|80.83333333333333|
| 28|  Male|    Loris Crossett|   OOP|8172914|   98|Paris Hutton_Pari...|        120|81.66666666666667|
| 28|  Male|    Loris Crossett|   OOP|9692316|   99|Judie Chipps_Mich...|        120|             82.5|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+

In [0]:
df_Cloud = student_data.filter( (student_data.course=='Cloud') & (student_data.average>60) )
df_Cloud.show()

+---+------+-----------------+------+-------+-----+--------------------+-----------+-----------------+
|age|gender|             name|course|   roll|marks|               email|total marks|          average|
+---+------+-----------------+------+-------+-----+--------------------+-----------+-----------------+
| 28|Female|     Claude Panos| Cloud|  72409|   85|Sheryll Towler_Al...|        120|70.83333333333334|
| 29|  Male|      Billi Clore| Cloud| 512047|   76|Taryn Brownlee_Ju...|        120|63.33333333333333|
| 28|Female|   Somer Stoecker| Cloud| 612490|   82|Sebrina Maresca_G...|        120|68.33333333333333|
| 29|Female|     Judie Chipps| Cloud| 632793|   75|Tijuana Kropf_Ele...|        120|             62.5|
| 29|Female|     Eda Neathery| Cloud|1011971|   91|Margene Moores_El...|        120|75.83333333333333|
| 28|  Male|   Bonita Higuera| Cloud|1312294|   94|Eda Neathery_Pris...|        120|78.33333333333333|
| 29|Female|  Hubert Oliveras| Cloud|1392791|   94|Anna Santos_Alber...|        120|78.33333333333333|
| 28|Female|      Neda Briski| Cloud|1651303|   74|Ernest Rossbach_D...|        120|61.66666666666667|
| 28|Female|   Melani Engberg| Cloud|1872667|   99|Alberta Freund_Ni...|        120|             82.5|
| 28|Female|     Paris Hutton| Cloud|2051881|   79|Melani Engberg_Ma...|        120|65.83333333333333|
| 28|Female|     Eda Neathery| Cloud|2071302|   95|Latia Vanhoose_Do...|        120|79.16666666666666|
| 28|  Male|      Neda Briski| Cloud|2092176|   81|Celeste Lollis_Ma...|        120|             67.5|
| 28|Female|    Tijuana Kropf| Cloud|2121632|   78|Michelle Ruggiero...|        120|             65.0|
| 28|Female|   Jenna Montague| Cloud|2402240|   96|Annika Hoffman_Du...|        120|             80.0|
| 29|Female|   Dustin Feagins| Cloud|2421900|   89|Niki Klimek_Latia...|        120|74.16666666666667|
| 28|Female|  Ernest Rossbach| Cloud|2602027|   83|Alberta Freund_Go...|        120|69.16666666666667|
| 28|  Male|Leontine Phillips| Cloud|3011586|   76|Dustin Feagins_Al...|        120|63.33333333333333|
| 29|Female|  Sebrina Maresca| Cloud|3261159|   97|Maybell Duguay_Ja...|        120|80.83333333333333|
| 28|  Male| Clementina Menke| Cloud|3352508|   95|Naoma Fritts_Mick...|        120|79.16666666666666|
| 28|  Male|    Kizzy Brenner| Cloud|3581303|   80|Margene Moores_Ta...|        120|66.66666666666666|
+---+------+-----------------+------+-------+-----+--------------------+-----------+-----------------+
only showing top 20 rows

In [0]:
df_OOP.select('name','marks').show()

+------------------+-----+
|              name|marks|
+------------------+-----+
|    Jenna Montague|   98|
|Priscila Tavernier|   99|
|      Judie Chipps|   99|
|    Margene Moores|   97|
|      Jc Andrepont|   97|
|    Loris Crossett|   98|
|    Loris Crossett|   99|
+------------------+-----+

In [0]:
df_Cloud.select(col('name').alias("Full Name"), col('marks').alias("Marks")).show()

+-----------------+-----+
|        Full Name|Marks|
+-----------------+-----+
|     Claude Panos|   85|
|      Billi Clore|   76|
|   Somer Stoecker|   82|
|     Judie Chipps|   75|
|     Eda Neathery|   91|
|   Bonita Higuera|   94|
|  Hubert Oliveras|   94|
|      Neda Briski|   74|
|   Melani Engberg|   99|
|     Paris Hutton|   79|
|     Eda Neathery|   95|
|      Neda Briski|   81|
|    Tijuana Kropf|   78|
|   Jenna Montague|   96|
|   Dustin Feagins|   89|
|  Ernest Rossbach|   83|
|Leontine Phillips|   76|
|  Sebrina Maresca|   97|
| Clementina Menke|   95|
|    Kizzy Brenner|   80|
+-----------------+-----+
only showing top 20 rows

In [0]:
student_data.select("gender").distinct().show()

+------+
|gender|
+------+
|Female|
|  Male|
+------+

In [0]:
student_data.filter(student_data.course=='DB').count()

Out[37]: 157

In [0]:
student_data.dropDuplicates(["name"]).count()

Out[38]: 50

In [0]:
#Quiz

In [0]:
student_data.select("age",'gender','course').distinct().show()

+---+------+------+
|age|gender|course|
+---+------+------+
| 28|Female|    DB|
| 28|Female|   MVC|
| 29|  Male|    PF|
| 28|Female|   OOP|
| 29|Female| Cloud|
| 29|  Male| Cloud|
| 29|Female|   DSA|
| 29|  Male|   OOP|
| 29|  Male|    DB|
| 28|Female|    PF|
| 29|Female|   MVC|
| 29|Female|    DB|
| 28|  Male|    PF|
| 28|Female| Cloud|
| 29|  Male|   MVC|
| 28|  Male|   OOP|
| 28|  Male|   DSA|
| 29|Female|    PF|
| 28|  Male|   MVC|
| 28|  Male|    DB|
+---+------+------+
only showing top 20 rows

In [0]:
student_data.dropDuplicates(["age",'gender',"course"]).show()

+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
|age|gender|            name|course|  roll|marks|               email|total marks|           average|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        120| 70.83333333333334|
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        120|49.166666666666664|
| 28|Female|    Jc Andrepont|   DSA|232060|   58|Billi Clore_Abram...|        120|48.333333333333336|
| 28|Female|    Cheri Kenney|   MVC|321816|   24|Kena Wild_Michell...|        120|              20.0|
| 28|Female|  Alberta Freund|   OOP|251805|   83|Annika Hoffman_Sh...|        120| 69.16666666666667|
| 28|Female|  Loris Crossett|    PF|332739|   62|Michelle Ruggiero...|        120| 51.66666666666667|
| 28|  Male|  Annika Hoffman| Cloud|722193|   55|Taryn Brownlee_El...|        120| 45.83333333333333|
| 28|  Male|   Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|        120|              30.0|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|26.666666666666668|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120| 57.49999999999999|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|              37.5|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        120| 51.66666666666667|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        120|24.166666666666668|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        120|29.166666666666668|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        120| 45.83333333333333|
| 29|Female|    Claude Panos|   OOP|542821|   28|Hubert Oliveras_P...|        120|23.333333333333332|
| 29|Female|  Loris Crossett|    PF|201487|   96|Elenore Choy_Lati...|        120|              80.0|
| 29|  Male|     Billi Clore| Cloud|512047|   76|Taryn Brownlee_Ju...|        120| 63.33333333333333|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        120|44.166666666666664|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
student_data.sort('age').show()

+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
|age|gender|            name|course|  roll|marks|               email|total marks|           average|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
| 28|Female|       Kena Wild| Cloud|221750|   60|Mitzi Seldon_Jenn...|        120|              50.0|
| 28|Female|   Tijuana Kropf|    PF|571047|   41|Loris Crossett_Se...|        120|34.166666666666664|
| 28|Female|    Jc Andrepont|   DSA|232060|   58|Billi Clore_Abram...|        120|48.333333333333336|
| 28|Female|    Cheri Kenney|   MVC|321816|   24|Kena Wild_Michell...|        120|              20.0|
| 28|Female|  Loris Crossett|    PF|332739|   62|Michelle Ruggiero...|        120| 51.66666666666667|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
| 28|Female|Mickey Cortright|   DSA|342003|   44|Mitzi Seldon_Jean...|        120|36.666666666666664|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120| 57.49999999999999|
| 28|  Male| Hubert Oliveras|   OOP|351719|   63|Lawanda Wohlwend_...|        120|              52.5|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        120|53.333333333333336|
| 28|  Male| Sebrina Maresca|    PF|361316|   62|Nicole Harwood_La...|        120| 51.66666666666667|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        120| 51.66666666666667|
| 28|  Male|   Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|        120|              30.0|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|              37.5|
| 28|  Male|Toshiko Hillyard|    DB|392218|   47|Leontine Phillips...|        120|39.166666666666664|
| 28|Female|  Maybell Duguay| Cloud|261439|   20|Nicole Harwood_Ju...|        120|16.666666666666664|
| 28|Female|   Kizzy Brenner| Cloud|402409|   27|Ernest Rossbach_G...|        120|              22.5|
| 28|Female|     Anna Santos|    DB|311589|   79|Celeste Lollis_Mi...|        120| 65.83333333333333|
| 28|  Male|    Elenore Choy|    PF|422704|   66|Marylee Capasso_N...|        120| 55.00000000000001|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|26.666666666666668|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
student_data.sort('age','marks').show()

+---+------+---------------+------+-------+-----+--------------------+-----------+------------------+
|age|gender|           name|course|   roll|marks|               email|total marks|           average|
+---+------+---------------+------+-------+-----+--------------------+-----------+------------------+
| 28|Female|   Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|        120|16.666666666666664|
| 28|Female| Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|        120|16.666666666666664|
| 28|  Male|Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|        120|16.666666666666664|
| 28|Female|Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|        120|              17.5|
| 28|  Male|    Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|        120|              17.5|
| 28|  Male|  Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|        120|              17.5|
| 28|  Male| Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|        120|              17.5|
| 28|  Male|    Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|        120|              17.5|
| 28|Female|   Cheri Kenney| Cloud|2281771|   22|Tamera Blakley_Ab...|        120|18.333333333333332|
| 28|Female|    Donna Yerby| Cloud|4392575|   22|Leontine Phillips...|        120|18.333333333333332|
| 28|  Male|   Eda Neathery|    PF|5082430|   22|Leontine Phillips...|        120|18.333333333333332|
| 28|  Male|    Anna Santos|    DB|9772185|   22|Kizzy Brenner_Ann...|        120|18.333333333333332|
| 28|  Male|  Santa Kerfien|   MVC|1992202|   23|Annika Hoffman_Ta...|        120|19.166666666666668|
| 28|Female|    Neda Briski|    PF|3251377|   23|Kizzy Brenner_Mic...|        120|19.166666666666668|
| 28|Female| Bonita Higuera| Cloud|6061881|   23|Dustin Feagins_La...|        120|19.166666666666668|
| 28|  Male|Gonzalo Ferebee|   OOP|7162059|   23|Melani Engberg_Me...|        120|19.166666666666668|
| 28|Female|  Santa Kerfien|   OOP|3931948|   24|Jeannetta Golden_...|        120|              20.0|
| 28|  Male| Bonita Higuera| Cloud|1401526|   24|Jc Andrepont_Cher...|        120|              20.0|
| 28|  Male|    Anna Santos|   OOP|1621905|   24|Elenore Choy_Sant...|        120|              20.0|
| 28|  Male| Alberta Freund| Cloud|1802934|   24|Maybell Duguay_Pa...|        120|              20.0|
+---+------+---------------+------+-------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
student_data.orderBy(student_data.age.asc(),student_data.marks.desc()).show()

+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
|age|gender|              name|course|   roll|marks|               email|total marks|          average|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
| 28|Female|    Melani Engberg| Cloud|1872667|   99|Alberta Freund_Ni...|        120|             82.5|
| 28|  Male|       Niki Klimek|   DSA|5172507|   99|Marylee Capasso_E...|        120|             82.5|
| 28|Female|      Judie Chipps|   OOP|5451977|   99|Tamera Blakley_Mi...|        120|             82.5|
| 28|Female|    Jalisa Swenson|   MVC|5712033|   99|Dustin Feagins_Hu...|        120|             82.5|
| 28|  Male|    Loris Crossett|   OOP|9692316|   99|Judie Chipps_Mich...|        120|             82.5|
| 28|  Male|  Clementina Menke|   DSA|2772189|   98|Donna Yerby_Judie...|        120|81.66666666666667|
| 28|  Male|    Jenna Montague|   OOP|3331161|   98|Leontine Phillips...|        120|81.66666666666667|
| 28|Female|      Judie Chipps|   DSA|4631068|   98|Toshiko Hillyard_...|        120|81.66666666666667|
| 28|Female|    Somer Stoecker|    PF|5882098|   98|Judie Chipps_Clem...|        120|81.66666666666667|
| 28|  Male|    Loris Crossett|   OOP|8172914|   98|Paris Hutton_Pari...|        120|81.66666666666667|
| 28|  Male|    Dustin Feagins|    DB|8871049|   98|Jenna Montague_Cl...|        120|81.66666666666667|
| 28|  Male|       Niki Klimek|    PF|3381919|   97|Hubert Oliveras_L...|        120|80.83333333333333|
| 28|  Male|      Jc Andrepont| Cloud|5202136|   97|Jc Andrepont_Kena...|        120|80.83333333333333|
| 28|Female|       Billi Clore|   DSA|6242097|   97|Jeannetta Golden_...|        120|80.83333333333333|
| 28|  Male|Priscila Tavernier|   MVC|7502427|   97|Alberta Freund_Ni...|        120|80.83333333333333|
| 28|  Male|   Marylee Capasso|    DB|1611411|   96|Annika Hoffman_Lo...|        120|             80.0|
| 28|Female|         Kena Wild|    PF|3291691|   96|Tamera Blakley_Na...|        120|             80.0|
| 28|Female|     Kizzy Brenner|   OOP|2542257|   96|Eda Neathery_Lawa...|        120|             80.0|
| 28|  Male|    Jenna Montague|   DSA|3721359|   96|Naoma Fritts_Kizz...|        120|             80.0|
| 28|Female|      Jc Andrepont|   MVC|2251960|   96|Somer Stoecker_Me...|        120|             80.0|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
only showing top 20 rows

In [0]:
#QUIZ

In [0]:
office_data = spark.read.options(header=True, inferSchema=True).csv('/FileStore/tables/OfficeData.csv')
office_data.printSchema()

root
 |-- employee_name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- state: string (nullable = true)
 |-- salary: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- bonus: integer (nullable = true)

In [0]:
sorted_bonus = office_data.sort('bonus')
sorted_bonus.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
+-------------+----------+-----+------+---+-----+

In [0]:
sorted_age_sal = office_data.orderBy(office_data.age.desc(),office_data.salary.asc())
sorted_age_sal.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
sorted_age_bonus_sal = office_data.sort( office_data.age.desc(), office_data.bonus.desc(), office_data.salary.asc() )
sorted_age_bonus_sal.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
student_data.show()

+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
|age|gender|            name|course|  roll|marks|               email|total marks|           average|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        120|49.166666666666664|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        120| 51.66666666666667|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|              37.5|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        120|24.166666666666668|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|26.666666666666668|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120| 57.49999999999999|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        120| 70.83333333333334|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        120|53.333333333333336|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|        120|              42.5|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        120|29.166666666666668|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        120|44.166666666666664|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|        120|              22.5|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        120| 45.83333333333333|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|        120|              35.0|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|        120|              22.5|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|        120|              30.0|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|        120|18.333333333333332|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|        120|46.666666666666664|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        120| 51.66666666666667|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
student_data.groupBy('gender').count().show()

+------+-----+
|gender|count|
+------+-----+
|Female|  501|
|  Male|  499|
+------+-----+

In [0]:
student_data.groupBy('course').avg('marks').show()

+------+------------------+
|course|        avg(marks)|
+------+------------------+
|    PF| 59.83734939759036|
|    DB|59.044585987261144|
|   MVC| 61.05095541401274|
|   DSA| 62.21590909090909|
| Cloud|59.598958333333336|
|   OOP|  58.6578947368421|
+------+------------------+

In [0]:
student_data.groupBy('age').count().show()

+---+-----+
|age|count|
+---+-----+
| 28|  494|
| 29|  506|
+---+-----+

In [0]:
student_data.groupBy('course','gender').count().show()

+------+------+-----+
|course|gender|count|
+------+------+-----+
|   OOP|  Male|   70|
|    DB|  Male|   82|
| Cloud|Female|  106|
|   MVC|  Male|   86|
|   DSA|Female|   98|
|    PF|  Male|   97|
|   MVC|Female|   71|
| Cloud|  Male|   86|
|    PF|Female|   69|
|   DSA|  Male|   78|
|    DB|Female|   75|
|   OOP|Female|   82|
+------+------+-----+

In [0]:
from pyspark.sql.functions import sum,avg,max,min,mean,count

In [0]:
student_data.groupBy('course').agg( count('*'), avg('marks'), min('marks'), max('marks'), mean('marks') ).show()

+------+--------+------------------+----------+----------+------------------+
|course|count(1)|        avg(marks)|min(marks)|max(marks)|        avg(marks)|
+------+--------+------------------+----------+----------+------------------+
|    PF|     166| 59.83734939759036|        20|        99| 59.83734939759036|
|    DB|     157|59.044585987261144|        20|        98|59.044585987261144|
|   MVC|     157| 61.05095541401274|        22|        99| 61.05095541401274|
|   DSA|     176| 62.21590909090909|        20|        99| 62.21590909090909|
| Cloud|     192|59.598958333333336|        20|        99|59.598958333333336|
|   OOP|     152|  58.6578947368421|        20|        99|  58.6578947368421|
+------+--------+------------------+----------+----------+------------------+

In [0]:
student_data.groupBy('course','gender').agg( count('*').alias('Count'), avg('marks').alias('Avg_Marks'), min('marks'), max('marks'), mean('marks') ).show()

+------+------+-----+------------------+----------+----------+------------------+
|course|gender|Count|         Avg_Marks|min(marks)|max(marks)|        avg(marks)|
+------+------+-----+------------------+----------+----------+------------------+
|   OOP|  Male|   70| 60.48571428571429|        20|        99| 60.48571428571429|
|    DB|  Male|   82| 61.86585365853659|        20|        98| 61.86585365853659|
| Cloud|Female|  106| 59.58490566037736|        20|        99| 59.58490566037736|
|   MVC|  Male|   86| 60.94186046511628|        22|        99| 60.94186046511628|
|   DSA|Female|   98| 62.48979591836735|        20|        99| 62.48979591836735|
|    PF|  Male|   97| 61.44329896907217|        20|        99| 61.44329896907217|
|   MVC|Female|   71|61.183098591549296|        22|        99|61.183098591549296|
| Cloud|  Male|   86|59.616279069767444|        21|        97|59.616279069767444|
|    PF|Female|   69| 57.57971014492754|        20|        99| 57.57971014492754|
|   DSA|  Male|   78| 61.87179487179487|        20|        99| 61.87179487179487|
|    DB|Female|   75|             55.96|        20|        96|             55.96|
|   OOP|Female|   82| 57.09756097560975|        21|        99| 57.09756097560975|
+------+------+-----+------------------+----------+----------+------------------+

In [0]:
student_data.groupBy('course').count().show()

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

In [0]:
student_data.groupBy('course').count().show()

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

In [0]:
student_data.groupBy('course').agg(count("*").alias("total")).where(col('total')>170).show()

+------+-----+
|course|total|
+------+-----+
|   DSA|  176|
| Cloud|  192|
+------+-----+

In [0]:
student_data.groupBy('course').agg(count("*").alias("total")).filter(col('total')>170).show()

+------+-----+
|course|total|
+------+-----+
|   DSA|  176|
| Cloud|  192|
+------+-----+

In [0]:
#QUIZ

In [0]:
student_data.show()

+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
|age|gender|            name|course|  roll|marks|               email|total marks|           average|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        120|49.166666666666664|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        120| 51.66666666666667|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|              37.5|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        120|24.166666666666668|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|26.666666666666668|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120| 57.49999999999999|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        120| 70.83333333333334|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        120|53.333333333333336|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|        120|              42.5|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        120|29.166666666666668|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        120|44.166666666666664|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|        120|              22.5|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        120| 45.83333333333333|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|        120|              35.0|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|        120|              22.5|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|        120|              30.0|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|        120|18.333333333333332|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|        120|46.666666666666664|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        120| 51.66666666666667|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
student_data.groupBy('course').count().show()

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

In [0]:
student_data.groupBy('course','gender').count().show()

+------+------+-----+
|course|gender|count|
+------+------+-----+
|   OOP|  Male|   70|
|    DB|  Male|   82|
| Cloud|Female|  106|
|   MVC|  Male|   86|
|   DSA|Female|   98|
|    PF|  Male|   97|
|   MVC|Female|   71|
| Cloud|  Male|   86|
|    PF|Female|   69|
|   DSA|  Male|   78|
|    DB|Female|   75|
|   OOP|Female|   82|
+------+------+-----+

In [0]:
student_data.groupBy('course','gender').sum('marks').show()

+------+------+----------+
|course|gender|sum(marks)|
+------+------+----------+
|   OOP|  Male|      4234|
|    DB|  Male|      5073|
| Cloud|Female|      6316|
|   MVC|  Male|      5241|
|   DSA|Female|      6124|
|    PF|  Male|      5960|
|   MVC|Female|      4344|
| Cloud|  Male|      5127|
|    PF|Female|      3973|
|   DSA|  Male|      4826|
|    DB|Female|      4197|
|   OOP|Female|      4682|
+------+------+----------+

In [0]:
student_data.groupBy('age','course').agg(min('marks'), max('marks'), avg('marks')).show()

+---+------+----------+----------+------------------+
|age|course|min(marks)|max(marks)|        avg(marks)|
+---+------+----------+----------+------------------+
| 29|   OOP|        20|        99|59.729729729729726|
| 28|    PF|        20|        98| 63.75949367088607|
| 28|    DB|        21|        98| 58.76829268292683|
| 28|   DSA|        20|        99|  64.6867469879518|
| 29|    DB|        20|        98|59.346666666666664|
| 28| Cloud|        20|        99|             58.08|
| 29|   DSA|        20|        99| 60.01075268817204|
| 28|   MVC|        23|        99| 60.44444444444444|
| 28|   OOP|        23|        99| 57.64102564102564|
| 29|    PF|        20|        99|56.275862068965516|
| 29|   MVC|        22|        99| 61.56470588235294|
| 29| Cloud|        21|        98|             61.25|
+---+------+----------+----------+------------------+

In [0]:
student_data.groupBy('course','age').agg(min('marks'), max('marks'), avg('marks')).show()

+------+---+----------+----------+------------------+
|course|age|min(marks)|max(marks)|        avg(marks)|
+------+---+----------+----------+------------------+
|   MVC| 28|        23|        99| 60.44444444444444|
|   MVC| 29|        22|        99| 61.56470588235294|
| Cloud| 28|        20|        99|             58.08|
|    PF| 29|        20|        99|56.275862068965516|
|    PF| 28|        20|        98| 63.75949367088607|
|   OOP| 29|        20|        99|59.729729729729726|
|   DSA| 28|        20|        99|  64.6867469879518|
| Cloud| 29|        21|        98|             61.25|
|    DB| 28|        21|        98| 58.76829268292683|
|   DSA| 29|        20|        99| 60.01075268817204|
|   OOP| 28|        23|        99| 57.64102564102564|
|    DB| 29|        20|        98|59.346666666666664|
+------+---+----------+----------+------------------+

In [0]:
worddata=sc.textFile('/FileStore/tables/WordData.txt')
worddata.collect()

Out[69]: ['Apple',
 'Mic',
 'Mic',
 'Apple',
 'Laptop',
 'Apple',
 'Mic',
 'Mic',
 'Apple',
 'Laptop',
 'Chair',
 'Chair',
 'Chair',
 'Bag',
 'Mobile',
 'Book',
 'Chair',
 'Chair',
 'Chair',
 'Bag',
 'Mobile',
 'Book',
 'Apple',
 'Mic',
 'Apple',
 'Mic',
 'Mic',
 'Apple',
 'Laptop',
 'Chair',
 'Chair',
 'Chair',
 'Bag',
 'Mobile',
 'Book',
 'Mic',
 'Apple',
 'Laptop',
 'Chair',
 'Chair',
 'Apple',
 'Mic',
 'Mic',
 'Apple',
 'Laptop',
 'Chair',
 'Chair',
 'Chair',
 'Bag',
 'Mobile',
 'Book',
 'Chair',
 'Bag',
 'Mobile',
 'Book']

In [0]:
worddata.map(lambda x: (x,1)).reduceByKey(lambda x,y:x+y).collect()

Out[70]: [('Apple', 10),
 ('Chair', 15),
 ('Bag', 5),
 ('Mobile', 5),
 ('Book', 5),
 ('Mic', 10),
 ('Laptop', 5)]

In [0]:
worddatadf = spark.read.csv('/FileStore/tables/WordData.txt')
worddatadf.show()

+------+
|   _c0|
+------+
| Apple|
|   Mic|
|   Mic|
| Apple|
|Laptop|
| Apple|
|   Mic|
|   Mic|
| Apple|
|Laptop|
| Chair|
| Chair|
| Chair|
|   Bag|
|Mobile|
|  Book|
| Chair|
| Chair|
| Chair|
|   Bag|
+------+
only showing top 20 rows

In [0]:
words = worddatadf.withColumnRenamed('_c0','words')
words.show()

+------+
| words|
+------+
| Apple|
|   Mic|
|   Mic|
| Apple|
|Laptop|
| Apple|
|   Mic|
|   Mic|
| Apple|
|Laptop|
| Chair|
| Chair|
| Chair|
|   Bag|
|Mobile|
|  Book|
| Chair|
| Chair|
| Chair|
|   Bag|
+------+
only showing top 20 rows

In [0]:
words.groupBy('words').count().show()

+------+-----+
| words|count|
+------+-----+
|   Mic|   10|
| Chair|   15|
|  Book|    5|
|Laptop|    5|
|   Bag|    5|
|Mobile|    5|
| Apple|   10|
+------+-----+

In [0]:
office_data.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

In [0]:
from pyspark.sql.types import IntegerType
def total_salary(x,y):
    return x+y;

total_salaryUDF = udf(lambda x,y: total_salary(x,y), IntegerType())

office_data.withColumn('total_salary', total_salaryUDF(office_data.salary, office_data.bonus)).show()

+-------------+----------+-----+------+---+-----+------------+
|employee_name|department|state|salary|age|bonus|total_salary|
+-------------+----------+-----+------+---+-----+------------+
|        James|     Sales|   NY| 90000| 34|10000|      100000|
|      Michael|     Sales|   NY| 86000| 56|20000|      106000|
|       Robert|     Sales|   CA| 81000| 30|23000|      104000|
|        Maria|   Finance|   CA| 90000| 24|23000|      113000|
|        Raman|   Finance|   CA| 99000| 40|24000|      123000|
|        Scott|   Finance|   NY| 83000| 36|19000|      102000|
|          Jen|   Finance|   NY| 79000| 53|15000|       94000|
|         Jeff| Marketing|   CA| 80000| 25|18000|       98000|
|        Kumar| Marketing|   NY| 91000| 50|21000|      112000|
+-------------+----------+-----+------+---+-----+------------+

In [0]:
from pyspark.sql.types import FloatType
def increment(salary, bonus, state):
    if state=='NY':
        return (0.05*bonus) + (0.1*salary)
    elif state=='CA':
        return (0.03*bonus) + (0.12*salary)

incrementUDF = udf(lambda x,y,z: increment(x,y,z), FloatType())

office_data.withColumn("increment", incrementUDF(office_data.salary, office_data.bonus, office_data.state)).show()

+-------------+----------+-----+------+---+-----+---------+
|employee_name|department|state|salary|age|bonus|increment|
+-------------+----------+-----+------+---+-----+---------+
|        James|     Sales|   NY| 90000| 34|10000|   9500.0|
|      Michael|     Sales|   NY| 86000| 56|20000|   9600.0|
|       Robert|     Sales|   CA| 81000| 30|23000|  10410.0|
|        Maria|   Finance|   CA| 90000| 24|23000|  11490.0|
|        Raman|   Finance|   CA| 99000| 40|24000|  12600.0|
|        Scott|   Finance|   NY| 83000| 36|19000|   9250.0|
|          Jen|   Finance|   NY| 79000| 53|15000|   8650.0|
|         Jeff| Marketing|   CA| 80000| 25|18000|  10140.0|
|        Kumar| Marketing|   NY| 91000| 50|21000|  10150.0|
+-------------+----------+-----+------+---+-----+---------+

In [0]:
# df.cache()
# df.rdd

In [0]:
student_data.createOrReplaceTempView('Student')

In [0]:
spark.sql('select * from Student limit 5;').show()

+---+------+----------------+------+-----+-----+--------------------+-----------+------------------+
|age|gender|            name|course| roll|marks|               email|total marks|           average|
+---+------+----------------+------+-----+-----+--------------------+-----------+------------------+
| 28|Female| Hubert Oliveras|    DB| 2984|   59|Annika Hoffman_Na...|        120|49.166666666666664|
| 29|Female|Toshiko Hillyard| Cloud|12899|   62|Margene Moores_Ma...|        120| 51.66666666666667|
| 28|  Male|  Celeste Lollis|    PF|21267|   45|Jeannetta Golden_...|        120|              37.5|
| 29|Female|    Elenore Choy|    DB|32877|   29|Billi Clore_Mitzi...|        120|24.166666666666668|
| 28|  Male|  Sheryll Towler|   DSA|41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
+---+------+----------------+------+-----+-----+--------------------+-----------+------------------+

In [0]:
spark.sql('select * from Student where average>50 order by average desc').show()

+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
|age|gender|              name|course|   roll|marks|               email|total marks|          average|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
| 29|Female|Priscila Tavernier|   OOP|3902993|   99|Celeste Lollis_Bi...|        120|             82.5|
| 29|Female|      Paris Hutton|   DSA| 271472|   99|Sheryll Towler_Al...|        120|             82.5|
| 29|  Male|    Maybell Duguay|    PF| 701486|   99|Clementina Menke_...|        120|             82.5|
| 29|  Male| Michelle Ruggiero|   DSA|1022971|   99|Cordie Harnois_Cl...|        120|             82.5|
| 28|Female|    Melani Engberg| Cloud|1872667|   99|Alberta Freund_Ni...|        120|             82.5|
| 28|  Male|       Niki Klimek|   DSA|5172507|   99|Marylee Capasso_E...|        120|             82.5|
| 28|Female|      Judie Chipps|   OOP|5451977|   99|Tamera Blakley_Mi...|        120|             82.5|
| 28|Female|    Jalisa Swenson|   MVC|5712033|   99|Dustin Feagins_Hu...|        120|             82.5|
| 29|  Male|   Gonzalo Ferebee|   MVC|5772006|   99|Niki Klimek_Marge...|        120|             82.5|
| 29|Female|    Alberta Freund|   DSA|6071316|   99|Dustin Feagins_Se...|        120|             82.5|
| 29|Female|      Eda Neathery|    PF|9222608|   99|Kena Wild_Lawanda...|        120|             82.5|
| 28|  Male|    Loris Crossett|   OOP|9692316|   99|Judie Chipps_Mich...|        120|             82.5|
| 29|  Male|    Alberta Freund|    DB|1671638|   98|Clementina Menke_...|        120|81.66666666666667|
| 28|  Male|  Clementina Menke|   DSA|2772189|   98|Donna Yerby_Judie...|        120|81.66666666666667|
| 29|  Male|    Melani Engberg|    DB|2941257|   98|Claude Panos_Kena...|        120|81.66666666666667|
| 28|  Male|    Jenna Montague|   OOP|3331161|   98|Leontine Phillips...|        120|81.66666666666667|
| 29|Female|  Clementina Menke|   DSA|3982381|   98|Tamera Blakley_Ki...|        120|81.66666666666667|
| 28|Female|      Judie Chipps|   DSA|4631068|   98|Toshiko Hillyard_...|        120|81.66666666666667|
| 28|  Male|    Loris Crossett|   OOP|8172914|   98|Paris Hutton_Pari...|        120|81.66666666666667|
| 28|Female|    Somer Stoecker|    PF|5882098|   98|Judie Chipps_Clem...|        120|81.66666666666667|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
only showing top 20 rows

In [0]:
#overwrite, ignore, append, error
office_data.write.mode('overwrite').options(header=True).csv('/FileStore/tables/output')